spring.application.name=gameboxd-backend
# 1. Conexión a tu base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gameboxd
spring.datasource.username=curso
spring.datasource.password=Curso2025.
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate (El traductor de Java a SQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' le dice a Java que actualice la BD si hay cambios, pero respetando lo que ya creamos
spring.jpa.hibernate.ddl-auto=update 
# Esto mostrará en la consola las consultas SQL que Java hace por debajo (muy útil para clase)
spring.jpa.show-sql=true